### ISSUE TITLE
Website Design is not at all responsive

### ISSUE THREAD

**Issue by robbyoconnor** [containers/podman.io_old#117]
## What are the issues
1. The nav menu should not dominate as it does for example on mobile: 
![image](https://user-images.githubusercontent.com/23088/60750264-0c20a700-9f74-11e9-9fd8-16d5e00bbc2f.png)

I have to actually scroll vertically to see the actual content which is bad design. This goes against every best practice. 

2. So much wasted space: 
![image](https://user-images.githubusercontent.com/23088/60750270-222e6780-9f74-11e9-85e9-3f3007378bfa.png)

3. The other issues are that your website should be self-contained...don't' link to the github markdown files, host them on the website. You folks could benefit from [Google Season of Docs](https://developers.google.com/season-of-docs/). 

## Proposals to improve it
I know my limits and frontend design is not my thing, but I do have proposals to fix it: 

Use bootstrap or another CSS framework to get responsiveness easy, or use a jekyll template that is known to work. Going the way you did is not good. I do not want to have people writing off podman because the website design isn't great. That more or less happened with me -- but fixing the design can make this turnaround.

**Comment by rhatdan** [comment]
Could you open a PR against podman.io to fix these issues.

**Comment by robbyoconnor** [comment]
From the initial comment at the start of "Proposals to improve it" heading: 

> I know my limits and frontend design is not my thing, but I do have proposals to fix it:

No -- I'm not redesigning the website, it's outside of my area of comfort. 

I opened an issue to give feedback and actual suggestions to improve it. I'm shocked there wasn't an issue like this prior.

**Comment by rhatdan** [comment]
Thanks @robbyoconnor.  It is also outside of my comfort zone.  I was hoping to get outside contributors to help with this issue.

The person in charge of the web sites is away on vacation right now.

**Comment by robbyoconnor** [comment]
it really does reflect poorly on the project -- esp. one with the backing of Red Hat when the website is this bad. It'd be better if the website simply didn't exist -- or heck just use sphinx with a reathedocs theme...anything is better than what you have right now.

**Comment by TomSweeneyRedHat** [comment]
@sanjabonic any thoughts/ideas?

**Comment by stappersg** [comment]
> it really does reflect poorly on the project -- esp. one with the backing of Red Hat when the website is this bad. It'd be better if the website simply didn't exist -- or heck just use sphinx with a reathedocs theme...anything is better than what you have right now.

With options
1. be better if the website simple didn't exist
2. just use sphinx with a reathedocs theme

I prefer option 2.

Yes, the _really does reflect poorly on the project_ is true.

**Comment by rhatdan** [comment]
@stappersg This is a community project, something the engineers are doing in the spare time.  We don't have a web site designer or documentation people working on this.  Red Hat Documentation and web site design go into products, not `projects`.   We need to rely on community to fixup the site.

We met last week to discuss how we want the web site to look ad have been working on a readthedocs site as well.
https://podman.readthedocs.io/en/latest/

If you would like to help improving the podman.io website, that would be welcome.

**Comment by robbyoconnor** [comment]
When I opened this issue -- I kept that in mind. I wanted to raise it as
an issue because it was necessary, but also wanted to do it in the most
tactful way possible...or at least not sound rude or condescending.

**Comment by pdfrod** [comment]
The currently used Jekyll theme (`jekyll-theme-dinky`) hasn't seen much love lately. Would you accept a pull request using a different theme?

**Comment by robbyoconnor** [comment]
@pdfrod I'm sure they'd love it -- can't speak for them -- you could also move it entirely to [Hugo](https://gohugo.io) as well.

**Comment by rhatdan** [comment]
We are a bunch of container programmers, not wed designers, so yes we would love community support on this.

**Comment by TomSweeneyRedHat** [comment]
@pdfrod we're always happy to take a PR.  Our main focus is to make sure that people can navigate through the site easily and that posts can be added to it without too much fuss.

**Comment by pdfrod** [comment]
Alright. My idea is just to touch up the UI to be cleaner and mobile friendly. Adding posts would continue to work the same through Jekyll.

I made a mockup of what I had in mind; let me know if I'm going in the right direction or if you simply wanted less drastic changes:

![mockup1](https://user-images.githubusercontent.com/227799/111405614-b8fb7300-86c8-11eb-8cb1-4a3aca5aeeab.png)


![mockup2](https://user-images.githubusercontent.com/227799/111405628-bd279080-86c8-11eb-8c35-ffc6240c25ba.png)

**Comment by robbyoconnor** [comment]
@pdfrod I really like this a lot -- it'd definitely increase my opinion of the project -- the website kinda soured me a little bit

**Comment by rhatdan** [comment]
LGTM, I like the new design a lot.

**Comment by robbyoconnor** [comment]
I would also like to apologize if this issue came off in any way rude, it was meant to be constructive criticism and left it open for someone to take up :)

**Comment by stappersg** [comment]
Do know that _perfect_ is the enemy of _good_.

**Comment by robbyoconnor** [comment]
I want it to be useable -- if people are looking at podman, they need to be able to find the information they need. 

I want it to be useable on all resolutions and screen-sizes.

**Comment by stappersg** [comment]
Make what you do more important than what you want

**Comment by robbyoconnor** [comment]
@stappersg in either case, there is an open PR and I tested it

**Comment by stappersg** [comment]
> there is an open PR

being #368
