### ISSUE TITLE
where is the registries.conf?

### ISSUE THREAD

**Issue by m4d3bug** [containers/podman.io_old#127]
**I started my podman with the following installation steps.**
``` bash
$ sudo apt install dirmngr \
software-properties-common
$ sudo add-apt-repository \
ppa:projectatomic/ppa
$ sudo apt update
$ sudo apt install -y podman buildah skopeo
```
**did not find /etc/containers/registries.conf.
and got this echo.**
``` bash
$ podman -v
podman version 1.5.0
WARN[0000] unable to find /etc/containers/registries.conf. some podman (image shortnames) commands may be limited
```
Here are my system info:
``` echo
$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l
$ uname -a
Linux alihk149 4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
On fedora registries.conf comes from the containers-common package.
@lsm5 PTAL

**Comment by m4d3bug** [comment]
any update？

> On fedora registries.conf comes from the containers-common package.
> @lsm5 PTAL

**Comment by rhatdan** [comment]
Easiest would be to just grab the registries.conf from https://github.com/containers/image/blob/master/registries.conf  and copy it to /etc/containers/registries.conf and populate it there.

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this as it's been a while and the issue should have been posted against the Podman project, not the blog project for Podman.  If this is still an issue, please open a new issue on https://github.com/containers/libpod/issues
