### ISSUE TITLE
Podman error to pull image from Artifactory

### ISSUE THREAD

**Issue by rodris-gimba** [containers/podman.io_old#135]
When i try to **pull any image from artifactory**, I received the error: 

> _ERRO[0001] error pulling image "registry:5000/base/base_alpine": unable to pull registry:5000/base/base_alpine: unable to pull image: Error initializing image from source docker://registry:5000/base/base_alpine: **invalid character '<' looking for beginning of value**_

The same image pulled with Docker doesn't return this error and the result is succesful.

Does anyone have the same problem or a solution for this? Thanks.

**Comment by TomSweeneyRedHat** [comment]
@rodris-gimba this project is used for the podman.io blog site.  The project where Podman lives and errors should be reported to is:  https://github.com/containers/libpod.  I've moved this issue there at: 
https://github.com/containers/libpod/issues/4254

I'm going to close this.
