### ISSUE TITLE
Getting Started page duplication

### ISSUE THREAD

**Issue by psimyn** [containers/podman.io_old#142]
The [Getting Started](https://podman.io/getting-started/) page only has two links: installation instructions and [getting-started/getting-started](https://podman.io/getting-started/getting-started).

Moving the actual instructions to `/getting-started` would save people an extra click. Especially not needed since the first step on `getting-started/getting-started` is 'Install'

**Comment by rhatdan** [comment]
@psimyn Could you open a PR to fix this?

**Comment by TomSweeneyRedHat** [comment]
@jberkus WDYT?

**Comment by TomSweeneyRedHat** [comment]
@psimyn thanks for the issue.  I'm only slightly hesitant to make the proposed change as @jberkus had set that page up and I think he'd plans for adding further links there, but I'm not 100% sure.  Would like to hear from him.

**Comment by psimyn** [comment]
sure, will wait and happy to make PR if needed. 

If the plan is adding more links we could add the list at the top, followed by content of the current `getting-started/getting-started` page.

thanks everybody

**Comment by jberkus** [comment]
Seems fine.  Really the current structure is there because I was copying over from libpod/installation direction.

**Comment by rhatdan** [comment]
Ok. @psimyn Please open a PR to clean this up.
