### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by pfix** [containers/podman.io_old#165]
The paragraph in  https://github.com/containers/podman.io/blob/master/getting-started/index.md#testing-the-httpd-server starts with "Now that we have the IP address of the container". But in the previous paragraph it is pointed out, that there is no IP address.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by daniel-schier** [comment]
If you need some support with the getting started guide, please feel free to give me a ping. :+1:

**Comment by TomSweeneyRedHat** [comment]
@daniel-wtd be my guest!  All help gratefully accepted!

**Comment by daniel-schier** [comment]
Started to work on this.

**Comment by TomSweeneyRedHat** [comment]
@daniel-wtd any progress?

**Comment by daniel-schier** [comment]
Hey sorry for the massive delay here. I am on it. Hope to get the guide done, soon.

**Comment by daniel-schier** [comment]
Hi, the guide is almost done (at least the markdown part). Is there some kind of build step that needs to be performed before openening a PR?

**Comment by TomSweeneyRedHat** [comment]
@daniel-wtd great news!  No build step needed before creating a PR.  We'll review it as an md file and then if necessary, it will be automatically converted once merged.

**Comment by daniel-schier** [comment]
PR is opened and feedback will be appreciated :)
