### ISSUE TITLE
podman cp container:dir_path/. existing_dir/ not working as expected

### ISSUE THREAD

**Issue by jvillal-amp** [containers/podman.io_old#168]
The docker docs https://docs.docker.com/engine/reference/commandline/cp/ say that when copying and the SRC_PATH ends with "/." and the DEST_PATH is a directory that it will copy the contents of SRC_PATH to DEST_PATH.

Podman is copying the SRC_PATH to DEST_PATH and not the contents of SRC_PATH.

For example I do:
```
$ podman cp --pause=false gracious_goodall:/root/. ~/output/
$ ls ~/output/
root
```

Which is not working as the 'docker cp' documentation says it should be. It should copy the "contents" of the /root/ directory and not the directory (including the directory name).

**Comment by rhatdan** [comment]
If you think this is a bug in podman please open an issue on github.com/containers/libpod.

**Comment by jvillal-amp** [comment]
> 
> 
> If you think this is a bug in podman please open an issue on github.com/containers/libpod.

Okay
