### ISSUE TITLE
Podman installation - Simple question

### ISSUE THREAD

**Issue by DSSDEV-Repo** [containers/podman.io_old#172]
Am I supposed to install Docker before installing Podman?

Does Podman require Docker in order to run correctly?

I assumed that Podman could be installed without Docker, but if I just install Podman, then a lot of things don't work properly.

**Comment by rhatdan** [comment]
Podman does not require Docker, the goal is a replacement of the Docker CLI.  Currently Podman does not support the Docker socket, so if you app requires access to the Docker socket, then Podman will not solve this.

If something does not work that you can do at the CLI, then we would love to hear these issues, reported at https://github.com/containers/libpod.

**Comment by DSSDEV-Repo** [comment]
I can not connect to my GitHub repository from PodMan.
And, I can not seem to get a login for my repository, on a server that does not have Docker installed already.
The repository was created, and accessed using standard Docker, and I can still get to it, using a server that has Docker installed on it, but not from the Podman only server.

**Comment by rhatdan** [comment]
I am not sure what commands are failing.  Could you give the exact command line that fails, on podman but works on Docker.

**Comment by TomSweeneyRedHat** [comment]
Closing this as we've not had a response in several months and the issue should really be logged against the development site [https://github.com/containers/libpod](https://github.com/containers/libpod)
