### ISSUE TITLE
Podman logos for each blog post

### ISSUE THREAD

**Issue by saschagrunert** [containers/podman.io_old#206]
Hey :wave:,

Just saw that we add the podman logo for each blog post which looks a bit noisy from my perspective:
![logos](https://user-images.githubusercontent.com/695473/76622188-4b56bd00-6531-11ea-83fb-dfa104b17b61.gif)

Do you think we could remove them and stick to a single logo on top?

**Comment by rhatdan** [comment]
@saschagrunert @TomSweeneyRedHat Any idea how to do this?

**Comment by TomSweeneyRedHat** [comment]
I do, but I prefer having them as breaks between the blogs.  @saschagrunert has been the only one so far that has asked for this change, so I've been letting it smolder.

**Comment by saschagrunert** [comment]
Yeah feel free to close if you think that the current layout is fine :)

**Comment by rhatdan** [comment]
Alright I will close.
