### ISSUE TITLE
Why my system logs flooded with message `container kill ... (image=..., name=...)` when I start container?

### ISSUE THREAD

**Issue by NTMan** [containers/podman.io_old#208]
Why my system logs flooded with message `container kill 8f3ff324c6a5188c9ff63ac3f870cc6c4ffc1a3046f4db025dc2d62f4de39f76 (image=dev-registry.sbis.ru/local_stand/inside:20.2100, name=inside)` when I start container?

[system-log.zip](https://github.com/containers/podman.io/files/4346986/system-log.zip)

```
$ podman --version
podman version 1.8.1-dev
```

[podman inspect inside](https://github.com/containers/podman.io/files/4346988/podman-inspect-inside.txt)

**Comment by TomSweeneyRedHat** [comment]
@NTMan thanks for the issue report, but you reported this against the blog site for Podman, not the development site.  I've created https://github.com/containers/libpod/issues/5537 for this issue, please follow up there as necessary.

Closing the issue here.
