### ISSUE TITLE
installation issue on ubuntu 19.10

### ISSUE THREAD

**Issue by Houuse** [containers/podman.io_old#215]
hi,
when I try to install podman for the first time on ubuntu 19.10
following the documentation
got this error
```
sudo apt-get update -qq
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_  Release' does not have a Release file.
W: GPG error: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4D64390375060AA4
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10  InRelease' is not signed.
```

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@Houuse what arch are you on btw?

**Comment by Houuse** [comment]
@lsm5 could extra info be more helpful ?

```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           24
Model name:                      AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1583.420
CPU max MHz:                     2100,0000
CPU min MHz:                     1400,0000
BogoMIPS:                        4191.71
Virtualization:                  AMD-V
L1d cache:                       128 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        4 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditional, STIBP disabled, RSB filling
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx1
                                 6 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate sme ssbd sev ibpb vmmcall
                                  fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif
                                  overflow_recov succor smca

```

**Comment by eriksjolund** [comment]
The installation instructions at
https://podman.io/getting-started/installation
have these lines
```
. /etc/os-release
sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:testing.list"
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
sudo apt-get update -qq
sudo apt-get -qq -y install podman
```

I made a test where I ran the installation instructions but leaving out `. /etc/os-release`

```
test@ubuntu1910:/tmp$ sudo sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:testing.list"
test@ubuntu1910:/tmp$ curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1103    0  1103    0     0   8967      0 --:--:-- --:--:-- --:--:--  8967
gpg: no valid OpenPGP data found.
test@ubuntu1910:/tmp$ sudo apt-get update -qq
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_  Release' does not have a Release file.
test@ubuntu1910:/tmp$ 
```

I see the same error message
```
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_  Release' does not have a Release file.
```

**Comment by lsm5** [comment]
looks like `${VERSION_ID}` doesn't evaluate to anything on your env, which is likely because you missed `. /etc/os-release` before running the other steps. Could you please retry with this?

This works on my ubuntu:19.10 container.

**Comment by rhatdan** [comment]
I am going to close this issue, since it does not seem to be a problem with Podman.  Also podman problems are better to report at github.com:containers/libpod.

**Comment by Houuse** [comment]
the problem was that` ${VERSION_ID}/ ` in the second command not being evaluated to any thing, 
hardcoding it solved the issue

**Comment by TomSweeneyRedHat** [comment]
@lsm5 is there a tweak to the install guide we could make to note @Houuse 's findings?

**Comment by Houuse** [comment]
just a note I'm using zsh
and I'm linux newbie

**Comment by lsm5** [comment]
> just a note I'm using zsh
> and I'm linux newbie

No problem at all. IIUC, zsh should be fully bash-compatible. I tried the install steps on ubuntu:19.10 container using zsh as well, and it worked.

Would you mind trying the two commands below on your zsh and posting the output?

```
. /etc/os-release
echo ${VERSION_ID}
```

On my zsh env, it said `19.10` which is what I got with bash as well.

**Comment by Houuse** [comment]
`. /etc/os-release` no output
`echo ${VERSION_ID}` output `19.10`

**Comment by guerra08** [comment]
I'm having the same issue on PopOs 20.04. `. /etc/os-release` yields no results. After that, when executing `curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - sudo apt-get update -qq` the "No OpenPGP key found" is returned.

**Comment by guerra08** [comment]
> I'm having the same issue on PopOs 20.04. `. /etc/os-release` yields no results. After that, when executing `curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - sudo apt-get update -qq` the "No OpenPGP key found" is returned.

After some tinkering, I was able to solve the problem. It was due to a backslash in the ${VERSION_ID}.

**Comment by TomSweeneyRedHat** [comment]
@lsm5?

**Comment by lsm5** [comment]
> > I'm having the same issue on PopOs 20.04. `. /etc/os-release` yields no results. After that, when executing `curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - sudo apt-get update -qq` the "No OpenPGP key found" is returned.
> 
> After some tinkering, I was able to solve the problem. It was due to a backslash in the ${VERSION_ID}.

@guerra08 that's weird, mind posting your $VERSION_ID please?

**Comment by lsm5** [comment]
ah PopOS! I remember we had accounted installation steps for PopOS, but gotta double-check. Is there an official PopOS container image available anywhere?

**Comment by guerra08** [comment]
> > > I'm having the same issue on PopOs 20.04. `. /etc/os-release` yields no results. After that, when executing `curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - sudo apt-get update -qq` the "No OpenPGP key found" is returned.
> > 
> > After some tinkering, I was able to solve the problem. It was due to a backslash in the ${VERSION_ID}.
> 
> @guerra08 that's weird, mind posting your $VERSION_ID please?

After getting the os release information, $VERSION_ID reports 20_04. I was able to install and pull a test image with no problems.

**Comment by ClaudioLazaro** [comment]
Hellow Following rigth way :

https://software.opensuse.org/download/package?package=catatonit&project=devel%3Akubic%3Alibcontainers%3Astable

**Comment by lsm5** [comment]
> Hellow Following rigth way :
> 
> https://software.opensuse.org/download/package?package=catatonit&project=devel%3Akubic%3Alibcontainers%3Astable

@ClaudioLazaro could you please create a new issue and give details about the errors you notice?

**Comment by leonardoheld** [comment]
Hardcoding worked fine for me. I was trying installing podman inside a Docker container with ubuntu 18.04 as the base, but during build time `. /etc/os-release` seems to take no effect, so `${VERSION_ID}` is evaluated to nothing, leading to the key errors.
