### ISSUE TITLE
baseurl uses http:// instead of https://

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman.io_old#220]
I get a baseurl starting with `http://`
```
$ curl -s https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo | grep baseurl
baseurl=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/
$ 
```
I would have expected a baseurl starting with `https://`

```
$ curl -s https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo | grep baseurl
baseurl=https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/
$ 
```

**Comment by TomSweeneyRedHat** [comment]
@eriksjolund I'm confused by this report?   This project is used for the Podman.io blog site and I'm not sure how this pertains?  If you meant to post this against the Podman project, which I'm still not sure about, please do so [here](https://github.com/containers/libpod/issues).

I'm going to close this issue.  If I'm mistaken and it is an issue with this site, please re-open and add a little more explanation.
