### ISSUE TITLE
Outdated "build from source" instructions

### ISSUE THREAD

**Issue by abitrolly** [containers/podman.io_old#227]
The [instruction to get the source code](https://podman.io/getting-started/installation#get-source-code) sounds strange for a project that uses `go` modules. Is it still actual? What is the minimal `go` version for building `podman` 1.9.x?

**Comment by TomSweeneyRedHat** [comment]
@abitrolly I've not used the instructions in a few weeks, but they held the last time I did so.  If you find that they are no longer valid, please let us know.  @vrothberg is my go mod person, perhaps he has thoughts.

I believe that you could build Podman with go v1.9.*.  However, due to security issues in go prior to version 1.12.12, I would not advise using that version or any prior to 1.12.12.

**Comment by abitrolly** [comment]
What is the point in maintaining compatibility with go v1.9 then?

**Comment by TomSweeneyRedHat** [comment]
@abitrolly might be end of day brain, but I don't think we're maintaining v1.9 compatibility.  The compilation might work with v1.9, but I'm not sure.  Did you spot something in the documents that said we supported v1.9?  If so, it's probably something that needs to be cleaned up.

**Comment by abitrolly** [comment]
@TomSweeneyRedHat my bad. The instructions mention `1.10.x`. I guess I mixed that number with version of `podman`. ) Anyway, for the latest `go` with support for modules there is no need to clone into this structure anymore.

```
GOPATH
└── src
    └── github.com
        └── containers
            └── libpod
```

**Comment by vrothberg** [comment]
Feel free to open a pull request but please make sure that all make targets (including tests) continue working. Although go allows to place the module anywhere, some tools and scripts may rely on the old GOPATH layout.

**Comment by rhatdan** [comment]
We support go 1.12 right now, although I would like to move to go.1.13.  I don't think we want to state we support anything less then 1.12.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Is this still an issue?

**Comment by abitrolly** [comment]
@rhatdan 

> Feel free to open a pull request but please make sure that all make targets (including tests) continue working. 

I can do PR to close this, but I can not make sure that all make targets continue working. Only if tests break.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan as far as I know this has been cleaned up with other revisions.  @abitrolly if you find otherwise, please feel free to reopen or to create a new issue as you think works best.

**Comment by abitrolly** [comment]
@TomSweeneyRedHat the instruction is still at https://podman.io/getting-started/installation#get-source-code
