### ISSUE TITLE
Anchors for headers would be helpful

### ISSUE THREAD

**Issue by abitrolly** [containers/podman.io_old#228]
I get get a link to page section only be looking at the source code, like https://podman.io/getting-started/installation#get-source-code It would be much more convenient if headers contained the anchors.

**Comment by rhatdan** [comment]
Please open a PR to make the change you want.

**Comment by TomSweeneyRedHat** [comment]
@abitrolly if by chance you don't have the time, could you explain a bit more.  Are you saying you'd like to see a list table of contents like thing at the top?  Something like the one at the top of this page?  https://github.com/containers/common/blob/master/SECURITY.md

**Comment by abitrolly** [comment]
@TomSweeneyRedHat just hover the mouse over rendered markdown headers and the anchor will appear. That will be enough.

@rhatdan I am not sure I am proficient enough in Jekyll to know how it is supposed to work. I thought there are people at RH who did this in the past, because it is so common.

**Comment by abitrolly** [comment]
Markup seems to be generated by theme, and asked here - https://github.com/pages-themes/dinky/issues/17

https://github.com/containers/podman.io/blob/dbc18d4ff3c5fa08fc1a1f9841524dbe5373f6af/_config.yml#L3

**Comment by rhatdan** [comment]
Sure, I am sure Red Hat has expertise, Just perhaps not on this team.  :^)

**Comment by Luap99** [comment]
@abitrolly I have added anchors with #260. So I believe this can be closed?

**Comment by abitrolly** [comment]
@Luap99 works perfectly. Good job. )
