### ISSUE TITLE
Broken link for Darwin installation

### ISSUE THREAD

**Issue by vijaymateti** [containers/podman.io_old#240]
Following link is broken on this page (https://podman.io/getting-started/installation) is broken.

Remote Client
Latest remote client for MacOS (https://storage.googleapis.com/libpod-master-releases/podman-remote-latest-master-darwin-amd64.zip)

it would be great if you can fix the link and provide some detailed steps to setup podman on OSX. Thank you!

**Comment by TomSweeneyRedHat** [comment]
@vijaymateti thanks for the heads up.
@lsm5 PTAL

**Comment by thisconnect** [comment]
Any news on this?

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
@rhatdan Looks like an easy fix, but what is https://storage.googleapis.com/libpod-master-releases/ ?

**Comment by TomSweeneyRedHat** [comment]
@ashley-cui where is  https://storage.googleapis.com/libpod-master-releases/ referenced?

**Comment by ashley-cui** [comment]
@TomSweeneyRedHat  The broken link for mac (and windows too is broken) was https://storage.googleapis.com/libpod-master-releases/podman-remote-latest-master-darwin-amd64.zip. I was going to just change it to the the github asset but wasn't sure if there was something official on the storage.googleapis

**Comment by TomSweeneyRedHat** [comment]
Thanks @ashley-cui , that's a reference I'm not familiar with.  @jwhonce did you put this together or know where it's moved to?
