### ISSUE TITLE
Broken link for Windows installation

### ISSUE THREAD

**Issue by geoalexidis** [containers/podman.io_old#246]
Under: https://podman.io/getting-started/installation the link: https://storage.googleapis.com/libpod-master-releases/podman-remote-latest-master-windows-amd64.msi doesn't work.

**Comment by TomSweeneyRedHat** [comment]
@geoalexidis thanks for the heads up.  Will see if I can track that down.  I'm not sure where it has gone to.

**Comment by rhatdan** [comment]
They are now under the individual release, rather then on the main page.  I am not sure if there is a way to get a permanent link to the latest release.

**Comment by geoalexidis** [comment]
Hey guys,

Thanks for the fast response.

I can now work with the Download in the Release Section.

You might want to point users to the release section in the meantime? -> https://github.com/containers/libpod/releases

I leave the issue open and up to you for following up.

Thanks and best regards

**Comment by mbbroberg** [comment]
This looks fixed by the PR merged above. @geoalexidis, could you confirm? Thanks!

**Comment by geoalexidis** [comment]
@mbbroberg Thanks looks fine.

Thanks everybody.

I'll close this now.
