### ISSUE TITLE
Gvisor support?

### ISSUE THREAD

**Issue by Manishfoodtechs** [containers/podman.io_old#247]
I want to know do podman compatible with gvisor . Being OCI and runsc , I believe it should, but just need confirmation.
Sorry, If it is a dumb question.
https://gvisor.dev/
gVisor is an application kernel, written in Go, that implements a substantial portion of the Linux system surface. It includes an Open Container Initiative (OCI) runtime called runsc that provides an isolation boundary between the application and the host kernel.

**Comment by TomSweeneyRedHat** [comment]
@Manishfoodtechs questions about Podman are better asked on the Podman Mailing list (Send an email to podman-join@lists.podman.io with the word "Subscribe" in the subject.), or on the repository for Podman [libpod](www.github.com/containers/libpod).  This site is for the blogs about Podman.

All that said, I'm guessing @rhatdan  or @mheon will be able to answer your question here.

**Comment by mheon** [comment]
We don't do any specific testing with `gvisor` but, last I heard, it was working. It only works as root, though - it requires privileges that rootless Podman does not have.

**Comment by Manishfoodtechs** [comment]
Thanks  @mheon  and @TomSweeneyRedHat Mheon.  I am closing this issue here and opening a fresh issue for everyone's benefit at libpod repository.
