### ISSUE TITLE
Expired key

### ISSUE THREAD

**Issue by valankar** [containers/podman.io_old#296]
Was trying to do an update on my Ubuntu machine:

Err:6 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease
  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by valankar** [comment]
Still a problem, any update?

**Comment by dcsouthwick** [comment]
same here, for 20.04 
```sh
❯ echo $VERSION_ID
20.04
❯ curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_$\{VERSION_ID\}/Release.key | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1103    0  1103    0     0   7767      0 --:--:-- --:--:-- --:--:--  7822
gpg: no valid OpenPGP data found.
```

perhaps a bash-ism failure, as hard-coding `$VERSION_ID` to `20.04` worked for me :) 


(I'm sure i'll be back for 21.04 when I forgot I did this...)

**Comment by lsm5** [comment]
@valankar I got bit by this myself, but I followed the steps from https://podman.io/getting-started/installation to add the repo again and it works for me now. I suspect this is an OBS issue and not really a packaging problem. I'll poke the OBS people soon.

Let me know if it works for you too.

**Comment by valankar** [comment]
@lsm5 Yes that worked, thanks!

**Comment by lukynmatuska** [comment]
You must import the key:
```
wget -qO - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | sudo apt-key add -
```

**Comment by NautillusSs** [comment]
> You must import the key:
> 
> ```
> wget -qO - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | sudo apt-key add -
> ```

Had the same issue on Raspbian 10. I just replaced the xUbuntu_20.04 version by Raspbian_10.

**Comment by rhatdan** [comment]
This does not look like an issue with podman.io.

**Comment by suridge** [comment]
> I suspect this is an OBS issue and not really a packaging problem. I'll poke the OBS people soon.

How do we poke the OBS people?  I'm getting this error trying to install podman on Ubuntu 20.04

```
  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
```

**Comment by luiscape** [comment]
The keys for Ubuntu 20.04 seem to be expired--it expired today.

```shell
$ curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_20.04/Release.key | gpg --show-keys
pub   rsa2048 2018-08-03 [SC] [expired: 2022-12-06]
      2472D6D0D2F66AF87ABA8DA34D64390375060AA4
uid                      devel:kubic OBS Project <devel:kubic@build.opensuse.org>
```

I figure that a new key needs to be generated and the repo updated with it.

**Comment by minato7** [comment]
Also, keys for Debian 11 have expired, we have rounded up here but unsure when or how to poke OBS people to regenerate keys.


curl -fsSL ### https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/Debian_11/Release.key | gpg --show-keys

pub   rsa2048 2018-08-03 [SC] [expired: 2022-12-06]
      2472D6D0D2F66AF87ABA8DA34D64390375060AA4
uid                      devel:kubic OBS Project <devel:kubic@build.opensuse.org>

**Comment by greenmang0** [comment]
> Also, keys for Debian 11 have expired, we have rounded up here but unsure when or how to poke OBS people to regenerate keys.

You can ping them on @obshq on Twitter.
https://twitter.com/obshq

**Comment by jan-dubsky** [comment]
@rhatdan Can you please point us to the right place where to escalate this issue?

**Comment by matthewdaclark** [comment]
Looking for update

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Unfortunately, the best person for this is @lsm5, and he's just stepped away for a lengthy and well-earned holiday.  I'll see what I can dig up, but the Debian keys are a lot of voodoo magic to me.

**Comment by TomSweeneyRedHat** [comment]
@siretart do you by chance have any thoughts on this?

**Comment by jan-dubsky** [comment]
I'm not certain how others use your packages, so if the work-flow I will describe is not compatible with work flow of others, feel free to correct me.

In our workflow, we pass you GPG key to `apt` trusted store manually. In other words, we just do something like:
```
$ wget -qO - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key > /etc/apt/trusted.gpg.d/obs.gpg
```

Consequently, the only thing we'd need you to do is to extend the GPG key expiry date. This can be done if you have the **private** GPG key. There are many manuals all over the internet how to do so. I will just post the first link google gave me: https://makandracards.com/makandra-orga/13644-what-to-do-when-your-gpg-pgp-key-expires

For us, it would be then sufficient if you published the extended **public** GPG key in the URL shared above in the `wget` example. Naturally there are also other sub-directories in the `stable` subtree and all should be updated as well. The important message here is that you shouldn't have to deal with Debian packaging at all and that the whole fix should be a few GPG commands followed by updating a few public files.

**Comment by TomSweeneyRedHat** [comment]
Or perhaps @vrothberg ?

**Comment by vrothberg** [comment]
I don't know either, sorry.

But I suggest to open a fresh and new issue, so we can track work and know once it's done.

**Comment by rachnajain-ibm** [comment]
@TomSweeneyRedHat We see issue in Ubuntu_18.04 also.
```
GPG error: http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease: The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
The repository 'http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  InRelease' is not signed.
```

is there any fix for this that can be done ASAP?

**Comment by kay-ramme** [comment]
I used a dirty workaround 

. /etc/os-release

echo "deb https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list

sudo apt-get -o Acquire::AllowInsecureRepositories=true  update
sudo apt install -y --allow-unauthenticated podman
sudo rm '/etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list'

may be that helps ;-)

**Comment by siretart** [comment]
@TomSweeneyRedHat sorry, I'm not familiar with OBS, but I know that maintaining backports and archives requires signficiant amount of work.

Getting ubuntu back in line is something that I'm currently looking at, but it requires solving things like https://bugs.launchpad.net/ubuntu/+source/containerd/+bug/1998847

**Comment by jan-dubsky** [comment]
> I used a dirty workaround
Yop, this works, but it's ugly and unsafe! Don't use that in production systems!

To be the issue is resolved. When I do:
```
$ wget -qO - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key
```
The key there is already extended till 2025. Recheck is your issue still persists and potentially import the extended GPG key.

**Comment by CaryJ** [comment]
While this is fixed for 20.04, it is not fixed for 18.04, yet.
`$ wget -qO - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/Release.key | gpg -v`
`pub   rsa2048 2018-08-03 [SC] [expired: 2022-12-06]`

**Comment by matthewdaclark** [comment]
Its fixed for 20.04?

Its still failing for me: (Ansible Task)
- name: Source release and add podman repo and Download the GPG key and Update using the new repository and install podman
  ansible.builtin.shell:
    cmd: "set -o pipefail && source /etc/os-release

          sudo sh -c \"echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/\
          xUbuntu_{{ v_podman_for_ubuntu_os_version }}/ /' > /etc/apt/\
          sources.list.d/devel:kubic:libcontainers:stable.list\"

          wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/\
          xUbuntu_{{ v_podman_for_ubuntu_os_version }}/Release.key -O- | sudo apt-key add -

          "
  args:
    executable: /bin/bash
  register: podman_gpg_response
  changed_when: podman_gpg_response.rc != 0

**Comment by whitehatbuds** [comment]
Debian_10 keys has also expired.
I ran
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key | apt-key add -
and then
RUN apt-key list | grep -A 1 expired

pub   rsa2048 2018-08-03 [SC] [expired: 2022-12-06]
      2472 D6D0 D2F6 6AF8 7ABA  8DA3 4D64 3903 7506 0AA4
uid           [ expired] devel:kubic OBS Project <devel:kubic@build.opensuse.org>

**Comment by whitehatbuds** [comment]
Does anyone have a workaround for this?
I did "apt-get --allow-unauthenticated update" and its still returning the error 

GPG error: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10  InRelease: The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10  InRelease' is not signed.

**Comment by kay-ramme** [comment]
pls see above for "unauthenticated" installation - but, do not use for production ..

**Comment by jan-dubsky** [comment]
I already see all `Debian` and `Ubuntu` keys updated with expiration date till 02/2025. I think we are done here. Everything should already work for all of you. Do not forget to fetch the new key first.

For maintainers: Thank you for resolving this issue. We all really appreciate that :)

See you all in 2025 :trollface:

**Comment by sintasy** [comment]
Are they?
```
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | gpg -v

sig        4D64390375060AA4 2022-12-07   [selfsig]
```

**Comment by jan-dubsky** [comment]
> Are they?
> 
> ```
> curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | gpg -v
> 
> sig        4D64390375060AA4 2022-12-07   [selfsig]
> ```

??
```
$ curl -s -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | gpg -v 2>/dev/null
pub   rsa2048 2018-08-03 [SC] [expires: 2025-02-14]
      2472D6D0D2F66AF87ABA8DA34D64390375060AA4
uid           devel:kubic OBS Project <devel:kubic@build.opensuse.org>
sig        4D64390375060AA4 2022-12-07   [selfsig]
sig        3B3011B76B9D6523 2018-08-03   [User ID not found]
```

I see expiry date in 2025.

It also doesn't feel right that you share one line of the command output and drop other 4 lines.

**Comment by sintasy** [comment]
Yeah, you are right, this one till 2025. The problem was with 
```
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.23/xUbuntu_20.04/Release.key | gpg -v
gpg: armor header: Version: GnuPG v1.4.5 (GNU/Linux)
pub   rsa2048 2018-08-03 [SC] [expired: 2022-12-06]
      2472D6D0D2F66AF87ABA8DA34D64390375060AA4
uid           devel:kubic OBS Project <devel:kubic@build.opensuse.org>
sig        4D64390375060AA4 2020-09-27   [selfsig]
sig        3B3011B76B9D6523 2018-08-03   [User ID not found]
```
For the previous one, I just took a look on the wrong line, that's my bad.

**Comment by jan-dubsky** [comment]
You are right. I checked only the `/stable/` subtree, not the `/stable:/` subtree (notice the colon char). Maintainers there are probably a few more places where the GPG key has to be updated.

As horfix for users: All those keys are the same, so you can use keys from the `/stable/` subtree even for `/stable:/` packages. It will work because it's just one public GPG key copied `n` times.

**Comment by evolart** [comment]
> You must import the key:
> 
> ```
> wget -qO - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key | sudo apt-key add -
> ```

Thanks for this, resolved the issue for me.

**Comment by Hi-Angel** [comment]
Tried both `pgp -v` solution as well as `apt-key` one. Imports seems to have went fine and the key matches, however the error still persists.

```bash
# curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key | gpg -v
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1093  100  1093    0     0   3628      0 --:--:-- --:--:-- --:--:--  3619
gpg: armor header: Version: GnuPG v1.4.5 (GNU/Linux)
pub   rsa2048 2018-08-03 [SC] [expires: 2025-02-14]
      2472D6D0D2F66AF87ABA8DA34D64390375060AA4
uid           devel:kubic OBS Project <devel:kubic@build.opensuse.org>
sig        4D64390375060AA4 2022-12-07   [selfsig]
sig        3B3011B76B9D6523 2018-08-03   [User ID not found]
# wget -qO - https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_22.04/Release.key | sudo apt-key add -
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK
# apt update
Hit:1 http://ru.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://ru.archive.ubuntu.com/ubuntu jammy-updates InRelease                                             
Hit:3 http://ru.archive.ubuntu.com/ubuntu jammy-backports InRelease                                                                 
Hit:4 http://ru.archive.ubuntu.com/ubuntu jammy-security InRelease                                                                  
Hit:5 https://packages.gitlab.com/runner/gitlab-runner/ubuntu jammy InRelease                                                       
Get:6 https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04  InRelease [1,262 B]
Err:6 https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04  InRelease
  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
Fetched 1,262 B in 1s (1,017 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
140 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04  InRelease: The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
W: Failed to fetch https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04/InRelease  The following signatures were invalid: EXPKEYSIG 4D64390375060AA4 devel:kubic OBS Project <devel:kubic@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by Hi-Angel** [comment]
So, repeating the part of [initial installation instructions](https://podman.io/getting-started/installation#ubuntu) about a key fixed the problem:

```bash
curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key \
  | gpg --dearmor \
  | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
    https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
  | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
```
