### ISSUE TITLE
Dead link in Posts of Interest

### ISSUE THREAD

**Issue by ocafebabe** [containers/podman.io_old#326]
Hi,

FYI I've found a dead link in the [Posts of Interest](https://podman.io/blogs/2020/12/07/podman-posts-of-interests.html) section: 
"_hostnextra.com site - Easy to Install Podman on Ubuntu 20.04 - Like the title says, how to easily install Podman on Ubuntu 20.04._"

https://github.com/containers/podman.io/blob/master/_posts/2020-12-07-podman-posts-of-interests.md

Thanks

**Comment by TomSweeneyRedHat** [comment]
Ouch, cut/paste error there.  Will go fixt that up and thanks for the heads up/issue @ocafebabe !

**Comment by TomSweeneyRedHat** [comment]
Hmm, I'm not sure why this didn't close automatically with the PR, but closing now.
