### ISSUE TITLE
Question: Crossposting blogs

### ISSUE THREAD

**Issue by daniel-schier** [containers/podman.io_old#353]
Hi all,

I am currently working on my own blog and therefore started a podman series. I have seen some cross posts from "Enable Sysadmin". Is it possible (in general) to cross post blogs from the below?

- fedoramagazine
- fedora community blog
- self-hosted blog / private blogs

Is there any guideline / best practice for the same?

**Comment by rhatdan** [comment]
My understanding, is that Google Search frowns on this and penalizes it.

Here is an article from medium.com on this subject.

https://help.medium.com/hc/en-us/articles/217991468-About-SEO-and-duplicate-content

**Comment by rhatdan** [comment]
We publish a lot at `Enable Sysadmin` since I believe this gets the biggest amount of "Administrator" types get to see it.  Then we link to the articles in podman.io and social media to it on linked in and twitter.

**Comment by daniel-schier** [comment]
Sure thing. :)

I thought more about this kind of stuff: https://podman.io/blogs/2021/01/23/podman-posts-of-interests.html, but only if the article is interesting for you. I am also ok with the other way around (writing something for podman.io and mentioning it on my blog as a reference).

**Comment by TomSweeneyRedHat** [comment]
Hi @daniel-wtd,

If you're thinking about replicating the blog posts from another site onto podman.io, then no, not a good idea.  However, I don't think there's a problem with creating a post like the podman-points-of-interest post that you pointed out with a quick intro to the topic(s) and then a link to the post on fedoramagazine or what have you.

We're also always interested in new post too, so if you'd like to put one together here, we'd be happy to entertain it.  If you put something together, please reference the main README.md for the required format of a post on the site, jeykll requires a few things, nothing major.

**Comment by daniel-schier** [comment]
Thanks a lot, I will do so. :)
