### ISSUE TITLE
http 301 to https for docs.podman.io

### ISSUE THREAD

**Issue by erisd** [containers/podman.io_old#366]
Would be nice to forward http to https for docs.podman.io

**Comment by TomSweeneyRedHat** [comment]
hmm, thought we did that.  I'll have to play.

**Comment by TomSweeneyRedHat** [comment]
Oh, and thanks for the heads up @erisd!

**Comment by erisd** [comment]
no problem, thanks for fixing :)

**Comment by TomSweeneyRedHat** [comment]
This has been fixed.
