### ISSUE TITLE
Long command-line options are not shown correctly on the man pages

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman.io_old#373]
On the web page
http://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html
there is the text

_–name, -n_

I would have expected to see two hyphens before _name_, i.e.

_--name, -n_

I think the same problem is present for all long command-line options and on all man pages.
I guess this is related to how the man pages are generated from the source code.
(Unfortunately I don't know about how that works)

**Comment by TomSweeneyRedHat** [comment]
Hmm, I could have sworn this was already reported, but I can't find it in the open or closed issues. But yes, the long options such as `--tty` are displayed as `-tty` (but with a longer single dash) throughout the man pages.  It's due to the software that we use that resolves the source`. md` to HTML.  We have tried to fix it, but keep running into roadblocks.  I think the best we managed to work up was to get the dashes to appear as they should, but the font was completely messed up and unreadable.  

If someone from the community has thoughts/pointers I'd appreciate hearing them.  The man pages reside on [readthedocs](https://readthedocs.org/) and are generated from the `.rst` and `.md` files under this directory: https://github.com/containers/podman/tree/master/docs/source

**Comment by eriksjolund** [comment]
Yes, I also remember there was an issue. I searched once more and found it:
https://github.com/containers/podman/issues/7474

This issue is not just about the appearance of the web page. Searching for long command-line options will also fail (for instance using ctrl-f in Google Chrome).

**Comment by TomSweeneyRedHat** [comment]
@eriksjolund thanks for proving that I've not lost it completely, but more importantly for the link to that.  I'll revisit this weekend and see if I can work anything up.

**Comment by eriksjolund** [comment]
@TomSweeneyRedHat Good to hear! I had the same experience. 

In _docs/remote-docs.sh_ there is a line where `pandoc` is used. 


```
esjolund@laptop:~/podman$ git remote -v
origin	https://github.com/containers/podman.git (fetch)
origin	https://github.com/containers/podman.git (push)
esjolund@laptop:~/podman$ git rev-parse HEAD
f3024b906ce717f7858c138a9c1daf72bdb8d132
esjolund@laptop:~/podman$ grep pandoc docs/remote-docs.sh 
    pandoc --ascii --lua-filter=docs/links-to-html.lua -o $TARGET/${file%%.*}.html $markdown
esjolund@laptop:~/podman$ 
```

I did a test and built this Dockerfile

```
FROM docker.io/library/fedora:33
RUN dnf -y install pandoc
```

and tried out two different input formats for pandoc


* `-f markdown`
* `-f gfm`


(The input format name `gfm` stands for _GitHub-Flavored Markdown_)
```
esjolund@laptop:~/podman$ curl -s http://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html | grep name | grep ", " |grep -v "Use the name" |grep -v viewport
<h2><strong>–name</strong>, <strong>-n</strong><a class="headerlink" href="#name-n" title="Permalink to this headline">¶</a></h2>
esjolund@laptop:~/podman$ podman run --rm -w /podman -v .:/podman localhost/pandoc bash -c "pandoc --ascii --lua-filter=docs/links-to-html.lua -o ./output.html docs/source/markdown/podman-generate-systemd.1.md ; cat output.html" | grep name | grep ", "|grep -v "Use the name"
<h4 id="name--n"><strong>&#x2013;name</strong>, <strong>-n</strong></h4>
esjolund@laptop:~/podman$ podman run --rm -w /podman -v .:/podman localhost/pandoc bash -c "pandoc --ascii -f markdown  --lua-filter=docs/links-to-html.lua -o ./output.html docs/source/markdown/podman-generate-systemd.1.md ; cat output.html" | grep name | grep ", "|grep -v "Use the name"
<h4 id="name--n"><strong>&#x2013;name</strong>, <strong>-n</strong></h4>
esjolund@laptop:~/podman$ podman run --rm -w /podman -v .:/podman localhost/pandoc bash -c "pandoc --ascii -f gfm --lua-filter=docs/links-to-html.lua -o ./output.html docs/source/markdown/podman-generate-systemd.1.md ; cat output.html" | grep name | grep ", "|grep -v "Use the name"
<h4 id="--name--n"><strong>--name</strong>, <strong>-n</strong></h4>
esjolund@laptop:~/podman$ 
```




Test result summary:

| test description | result |  comment | 
| -                        | -        | - | 
| download official web page (curl) | `<strong>–name</strong>` |  a longer dash|
| pandoc without `-f` | `<strong>&#x2013;name</strong>` | `&#x2013;` seems to be a longer dash |
| pandoc with `-f markdown` | `<strong>&#x2013;name</strong>` | `&#x2013;` seems to be a longer dash |
| pandoc with `-f gfm` | `<strong>--name</strong>` | two standard dashes |






I think it is possible to customize pandoc with extensions:

```
esjolund@laptop:~/podman$ podman run --rm -w /podman -v .:/podman localhost/pandoc bash -c "pandoc --list-extensions=gfm"
+all_symbols_escapable
-ascii_identifiers
+auto_identifiers
+autolink_bare_uris
+backtick_code_blocks
-east_asian_line_breaks
+emoji
+fenced_code_blocks
+gfm_auto_identifiers
-hard_line_breaks
+intraword_underscores
+lists_without_preceding_blankline
+pipe_tables
+raw_html
-raw_tex
+shortcut_reference_links
-smart
+space_in_atx_header
+strikeout
+task_lists
esjolund@laptop:~/podman$ 
```
Quote from https://pandoc.org/MANUAL.html:
_Extensions can be individually enabled or disabled by appending +EXTENSION or -EXTENSION to the format name._

Maybe switching to `-f gfm` will improve the result?

**Comment by TomSweeneyRedHat** [comment]
@eriksjolund the `-f gfm` addition sounds completely reasonable to me.  Do you want to spin up a PR in Podman and give it a go?

**Comment by eriksjolund** [comment]
Yesterday I tried to create a container in which I could generate the whole web site. This is how far I got:

```
FROM docker.io/library/fedora:33

RUN dnf -y install python3-pip findutils make less golang pandoc && mkdir /output && pip3 install recommonmark sphinx-markdown-tables
```

I noticed that the script seemed to work differently on Windows and Linux so I assumed that a Windows computer is needed to generate the web pages and then I gave up.
```
[esjolund@laptop podman]$ grep -B6 -A2 PUBLISHER=html_fn docs/remote-docs.sh
case $PLATFORM in
darwin|linux)
    PUBLISHER=man_fn
    ext=1
    ;;
windows)
    PUBLISHER=html_fn
    ext=1.md
    ;;
[esjolund@laptop podman]$ 
```

Is there an easy way to generate the web pages on Linux? (Preferably in a container)

**Comment by TomSweeneyRedHat** [comment]
@eriksjolund we probably need to hear from @baude on this then, you've gotten further than I.  This [page]( https://github.com/containers/podman/blob/54b82a175f16f27849e6791f65bf73eccae4701a/docs/Readme.md) documents the conversion process, but from what I remember looking at this last summer/fall, the problem point is the ReadTheDocs site does processing of the md files.

Is it worth changing this line:  https://github.com/containers/podman/blob/a1b942ff401a9315dae05d9a3210780823d12839/docs/remote-docs.sh#L73 and adding the `-f gfm`  to it and see how that goes?  We could try it today while it's quiet, then revert if it's a problem.

**Comment by eriksjolund** [comment]
Do you mean something like this?
https://github.com/containers/podman/compare/master...eriksjolund:pandoc_gfm

The change will probably fix this issue (but I don't know if it will introduce new problems). I haven't for instance looked at the generated output together combined with CSS files.

**Comment by Luap99** [comment]
This can be closed, see https://github.com/containers/podman/pull/9856 and  https://docs.podman.io/en/latest/markdown/podman-attach.1.html

**Comment by TomSweeneyRedHat** [comment]
Closed by https://github.com/containers/podman/pull/9856

**Comment by eriksjolund** [comment]
Thanks, https://github.com/containers/podman/pull/9856 fixed most of them!

I noticed that there are some left.

#### Edit

I moved the contents of this comment into a new issue instead.
https://github.com/containers/podman.io/issues/389
