### ISSUE TITLE
Documentation: Command pages are all titled "NAME - Podman documentation"

### ISSUE THREAD

**Issue by rcowsill** [containers/podman.io_old#385]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

All pages linked from http://docs.podman.io/en/latest/Commands.html have the same title: "NAME - Podman documentation". This shows up in browser tabs, as well as in search results.

The search results would be much easier to navigate if they prominently showed the command names. Having clear titles for each page is also helpful when keeping multiple tabs open for reference.

**Steps to reproduce the issue:**

1. Visit https://docs.podman.io/en/latest/markdown/podman-info.1.html
2. Observe page title as shown in the browser tab
3. Visit https://docs.podman.io/en/latest/Search.html
4. Type "all" in the search box and click the Search button
5. Observe the results

**Describe the results you received:**
Step 2: Browser tab shows title "NAME - Podman documentation":

![info](https://user-images.githubusercontent.com/42620235/115567545-45deb100-a2b3-11eb-8ba5-0c19255f6a04.png)

Step 5: Results given are all titled "NAME":

![search](https://user-images.githubusercontent.com/42620235/115567583-52fba000-a2b3-11eb-8324-970f1e7cbbe7.png)

**Describe the results you expected:**

Step 2: Browser tab shows title (eg) "podman-info - Podman documentation"
Step 5: Search result links show the command name so it's clear which page they link to.

**Comment by rcowsill** [comment]
Sorry, I thought this belonged on containers/podman as that's where the source for docs.podman.io lives (https://github.com/containers/podman/tree/master/docs)

**Comment by rhatdan** [comment]
It does.  I don't think this is podman.io, if you have knowledge of how this works, would you be interestedin opening a PR?

**Comment by TomSweeneyRedHat** [comment]
Yes, this should be in Podman, but I'll leave it here for now.  Podman has all of the code for the man pages and we just do some dns routing from podman.io to create the "docs.podman.io" landing pad for the docs.

Regardless, @rcowsill excellent eyeballs on that, TYVM for reporting.  I don't have ideas on how to make it work better atm, but happy to take suggestions or better yet, a PR.

**Comment by rcowsill** [comment]
I've looked into it a little and am not sure of the best solution.

The title is currently taken from the first heading on each page, so the simple answer is to make that title the name of the command. I guess it's not like that already because the markdown is also used to generate man pages.

If making that change isn't an option then maybe there's some way to override the page title in recommonmark.

**Comment by rhatdan** [comment]
Is there any sed or bash hacking that we could do to fix this?

**Comment by rcowsill** [comment]
Enabling recommonmark's AutoStructify component will let us [embed a block of RST](https://github.com/readthedocs/recommonmark/blob/master/docs/auto_structify.md#embed-restructuredtext) to set the HTML document title. It shouldn't affect the man page output either, but I still need to test that.

**Comment by TomSweeneyRedHat** [comment]
@rcowsill TYVM for digging at this, the effort is very much appreciated.

**Comment by rcowsill** [comment]
Unfortunately the manpage build uses go-md2man, which doesn't understand eval_rst blocks. They get emitted into the output as a code block.

We could use sed to convert the existing pandoc-style title line (`% document title`) into an eval_rst block for the HTML build, but sphinx currently runs against the whole `source/markdown` directory. I think that would require preprocessing the markdown directory into a temporary path, rather than just pipelining it as with the manpage build.

Alternatively we could add an eval_rst block setting the title in each markdown source. With sed that could either be removed or converted into pandoc format for the manpage build. That seems like the path of least resistance.

**Comment by TomSweeneyRedHat** [comment]
@rcowsill well that doesn't sound like a quick flip of a switch kind of thing, unfortunately.  We were discussing during a meeting earlier today about wanting to get some files from other repos in there for processing too.  Files such as containers.conf and storage.conf.  @rhatdan said he has a script that he uses to do that copying, perhaps it can be combined?

**Comment by rhatdan** [comment]
This is the script that Fedora is using to update these configuration files while building packages for a release.
[containers-common.spec](https://github.com/containers/podman.io/files/6385023/containers-common.spec.txt)
[update.sh](https://github.com/containers/podman/files/6384993/update.sh.txt)

**Comment by rcowsill** [comment]
I found a way to apply the correct titles within the Sphinx build, which avoids changing the markdown files and manpage build process. PR is on the way...

As an aside, the windows podman-remote docs have the same issue. They're HTML pages built from the markdown using pandoc, but pandoc only sets titles when run with `--standalone`. Would a PR to change that be desirable?

**Comment by TomSweeneyRedHat** [comment]
@rcowsill awesome news.  A PR to touch up the podman-remote docs would be very desirable, thanks!
