### ISSUE TITLE
Dead links to seccomp.json and mounts.conf on /getting-started/installation

### ISSUE THREAD

**Issue by smkuehnhold** [containers/podman.io_old#390]
Howdy!

I am missing some configuration files after building from source (seccomp.json, mounts.conf).  I have tried following the guide located at https://podman.io/getting-started/installation , but am unable to get these files because the provided links are dead. I am not very knowledgeable, so I do not know where to find these files elsewhere. Do you mind providing them to me?

Thanks!

**Comment by TomSweeneyRedHat** [comment]
@smkuehnhold thanks for the heads up.  @rhatdan just updated the page, if you have further difficulties, please let us know.
