### ISSUE TITLE
Outdated "what is Podman?" page

### ISSUE THREAD

**Issue by BjoernPetersen** [containers/podman.io_old#391]
The ["Out of scope" section](https://podman.io/whatis.html#out-of-scope) of the "what is Podman?" page, which is referenced on the main page, is outdated. It still contains a whole paragraph about why Podman won't support docker-compose, but it's been supported [since Podman 3.0](https://www.redhat.com/sysadmin/podman-docker-compose).

**Comment by rhatdan** [comment]
Interested in opening a PR to fix?

**Comment by TomSweeneyRedHat** [comment]
Thanks @BjoernPetersen @rhatdan @mheon @fatherlinux we probably ought to revamp it.  We talk about the upcoming REST API and varlink.

**Comment by BjoernPetersen** [comment]
@rhatdan usually I'd love to, but I've literally taken my first look at Podman two days ago and probably shouldn't write its official description 😄

**Comment by rhatdan** [comment]
Fixed in https://github.com/containers/podman.io/pull/395

**Comment by TomSweeneyRedHat** [comment]
Closed with #395
