### ISSUE TITLE
RedHat8 installation instructions

### ISSUE THREAD

**Issue by joachimBurket** [containers/podman.io_old#394]
Hey,

It would be great if you could add in the installation instructions for "RHEL8 Beta", that the module `container-tools:1.0` is the stable stream version, and that there is also a "fast stream version" (`container-tools:rhel8`) available to have more recent version of the tools.
As the stable stream has pretty old tools (podman-1.0.2), some users might want to use the fast stream.

**Comment by rhatdan** [comment]
We would figure most users would want to fast stream.
@jnovy @lsm5 PTAL

**Comment by lsm5** [comment]
@joachimBurket would you like to create a PR for this?

I think the instructions should just say `RHEL 8` since we're way past 8 Beta.

**Comment by joachimBurket** [comment]
Sure :)
