### ISSUE TITLE
docs.podman.io version links aren't HTTPS

### ISSUE THREAD

**Issue by adrian5** [containers/podman.io_old#441]
On [docs.podman.io](https://docs.podman.io/) the version links presented when clicking on **v:latest** all use `http://` URLs that don't upgrade to `https://` (for me) when visited. Consider changing them to `https://`.

**Comment by rhatdan** [comment]
Please open a PR to make the change.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by adrian5** [comment]
I just saw [#11186](https://github.com/containers/podman/discussions/11186), which I think can be waited for instead. Feel free to close this issue in that case.

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this.  As it turns out, there was a check box deep down in our ISP control panel that was unchecked to force HTTPS.  I've just clicked that box and everything is using https now.
