### ISSUE TITLE
Permission to translate blog posts

### ISSUE THREAD

**Issue by tnk4on** [containers/podman.io_old#455]
I would like to translate some of the blog posts published on Podman.io.
Do I need to ask the author for permission in any way?

I plan to post the translated article on the Red Hat Japan blog.
https://rheb.hatenablog.com/

**Comment by rhatdan** [comment]
If they are Red Hat authors, then their should be no problem.  Other authors you should get permission from.

**Comment by TomSweeneyRedHat** [comment]
@tnk4on Thanks for taking this on!

As @rhatdan noted, feel free for any Red Hat authored post.  I believe most of the other authors would be just fine with the translation too, but I'd hit each one up with a quick email.

If you need any help outside of the actual translation, please let me know.

t

**Comment by tnk4on** [comment]
Thank you for confirming! I posted the first translated article.
https://rheb.hatenablog.com/entry/podman-on-macs

As with other translated articles, I wrote link back to the original English version at the beginning article and this, "Translated with permission from Podman.io."

**Comment by rhatdan** [comment]
Awesome thanks.  We can start adding links on podman.io

**Comment by TomSweeneyRedHat** [comment]
@tnk4on thanks!  WIll there be a top-level link we could add somewhere that would point to the translated Podman articles?

**Comment by tnk4on** [comment]
@TomSweeneyRedHat Currently, the link to the translated source article is set as follows in Markdown in the article writeup.

```
[Podman on Macs Update](https://podman.io/blogs/2021/09/06/podman-on-macs.html) 
```

Sorry for the confusion, the link is white in the CSS design.
It is also possible to display the title and link separately. Would this be better?

```
Podman on Macs Update
[https://podman.io/blogs/2021/09/06/podman-on-macs.html](https://podman.io/blogs/2021/09/06/podman-on-macs.html)
```

**Comment by TomSweeneyRedHat** [comment]
@tnk4on Thanks, but what I was hoping for is that you will translate several posts over time.  Will you have a link that I could send people to and they would then be able to see all the posts you had translated to that point?  The links that you sent me prior worked fine, I am just hoping to not have to create a link on the site for each post that you translate.

**Comment by tnk4on** [comment]
@TomSweeneyRedHat 
I have created a fixed page. This is a list of translated articles that have been posted on this blog in the past.
How about using this link?
https://rheb.hatenablog.com/podman-jp-translate

I plan to continue with Podman related translated articles in the future. Where would be the appropriate place to continue to communicate about translations? (IRC/Discord ? or GitHub discussion ?)
