### ISSUE TITLE
Podman Auto-Update

### ISSUE THREAD

**Issue by mprofitt** [containers/podman.io_old#460]
Following "Autoupdate with local policy" example with Debian 11...
https://manpages.ubuntu.com/manpages/impish/man1/docker-auto-update.1.html

I keep getting this error and unable to resolve.
Error: 2 errors occurred:
        * invalid auto-update policy "local": valid policies are ["disabled" "image"]
        * invalid auto-update policy "local": valid policies are ["disabled" "image"]
I have 2 different containers configure, one of them is the busybox:latest as shown in the example.

Thanks,
Mike

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, Mike.

Podman in Debian 11 does not support the "local" policy; it has been added with a later version.  I suggest having a look at the Debian man pages instead.
