### ISSUE TITLE
Installation instruction for Ubuntu with kubic ppa are deprecated

### ISSUE THREAD

**Issue by GordianDziwis** [containers/podman.io_old#481]
They do not work anymore, [here](https://software.opensuse.org//download.html?project=devel%3Akubic%3Alibcontainers%3Astable&package=podman) are the current working ones.

**Comment by lsm5** [comment]
Kubic installation steps have now been removed. See: https://podman.io/blogs/2022/04/05/ubuntu-2204-lts-kubic.html 

Closing.
