### ISSUE TITLE
Can podman use cluster mode?

### ISSUE THREAD

**Issue by ThorManager** [containers/podman.io_old#486]
We can't use k8s in our environment. Is there any other cluster technology that can be implemented? such as docker swarm？

**Comment by rhatdan** [comment]
No, we have no intention of implementing Docker Swarm.

**Comment by rhatdan** [comment]
Why is K8s not allowed?

**Comment by TomSweeneyRedHat** [comment]
@ThorManager your questions are always welcomed, but as an FYI, if you have a question like this one that is Podman specific, it is probably better to create an issue on the [Podman](https://github.com/containers/podman/issues) project's repo.  You'll get more of the Podman maintainers looking at it there than here.  This project is just for the podman.io website and fewer of the maintainers watch this one.
