### ISSUE TITLE
Windows installation broken link

### ISSUE THREAD

**Issue by javatlacati** [containers/podman.io_old#501]
on https://podman.io/getting-started/installation#windows if you click the link that says [Latest remote client for Windows](https://github.com/containers/podman/releases/latest/download/podman-remote-release-windows.zip) you will get to a screen that says not found

**Comment by TomSweeneyRedHat** [comment]
this has been updated, the link has been removed an replaced with page devoted to [Windows installation](https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md).
