### ISSUE TITLE
Enable "require sign-off on web-based commits" in repository settings

### ISSUE THREAD

**Issue by bluikko** [containers/podman.io_old#581]
If the repository policy is that commits must have sign-offs, then it would be helpful to enable the setting [Require contributors to sign off on web-based commits](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-the-commit-signoff-policy-for-your-repository#enabling-or-disabling-compulsory-commit-signoffs-for-your-repository) in repository settings.

Then when someone, likely a new contributor who does not know about the requirement, does a simple PR using the GitHub web interface - say, a trivial docs update - then there will be a tickbox "enable sign-off" when doing the commit.

**Comment by rhatdan** [comment]
Done

**Comment by lsm5** [comment]
> Done

guess we can close this then. @bluikko please reopen if you still see the issue. Thanks
