### ISSUE TITLE
Podman.io official website- obfuscated menu

### ISSUE THREAD

**Issue by Navid61** [containers/podman.io_old#591]
Hi,
I opened "https://podman.io/" website in last version of Firefox and Microsoft edge browsers but some items in side menu are not readable.

![podma_firefox_website](https://user-images.githubusercontent.com/4729469/222886707-562d1ac1-d1d6-4464-9a0c-6a3dbc290709.png)
![podman_edge](https://user-images.githubusercontent.com/4729469/222886710-a8a2fa60-ce12-4d84-8fe5-5a10048f8b91.png)
![podman_edge_website](https://user-images.githubusercontent.com/4729469/222886711-80faaeef-a336-4fda-9a8c-624b22115cfa.png)
![podman_firefox](https://user-images.githubusercontent.com/4729469/222886713-7d9e8499-8989-4d1a-847d-f146e61ef698.png)

**Comment by TomSweeneyRedHat** [comment]
@Navid61 thanks for the report.  That's unfortunately a problem that's hard coded into the current web page generating system that we're using on GitHub.  If you expand the size of your web browser, making it taller, the lines should "pull apart" and you'll see the links.

We are undertaking a massive redesign of the site at the moment to take care of this, and a number of other quality of life issues.  Once complete, it should share a lot of the look and feel of Podman Desktop, if you're familiar with that.  We're hoping to have the revamped site up in the early summer of 2023.

HTH!
