### ISSUE TITLE
Unclear from website what Podman does

### ISSUE THREAD

**Issue by wjt** [containers/podman.io_old#83]
My understanding is that the important features of Podman, in isolation, are:

* it can pull, create, run and manage containers
* it supports the OCI and Docker image formats
* it runs each container directly, not via a system daemon
* it does not need any privileges on the host system

(Maybe I'm wrong!) But if you don't already know what Podman is, https://podman.io/ is surprisingly little help. It has this to say:

> Manage pods, containers, and container images.

> What is Podman? Simply put: `alias docker=podman`

This may be true, but it doesn't explain why you would want to use podman rather than Docker.

If you drill down into https://podman.io/releases/ we get a bit closer (emphasis mine):

> Our original goal with Podman was to provide a fully-featured debugging experience for CRI-O, but it has become so much more. Podman 1.0.0 is a fully-featured container engine. **It provides a Docker-compatible command line to ease the transition from other container engines. Most Podman commands can be run as a regular user, without requiring additional privileges. Furthermore, all of this is accomplished without a daemon!**

https://github.com/containers/libpod#readme is also linked, and from there you can get to
https://github.com/containers/buildah/tree/master/docs/containertools#readme which is also a bit more informative. It would be nice if the front page of the website included some of this information.

**Comment by rhatdan** [comment]
@wjt Thanks for your input.  We would love to have you open a PR to change this to look the way you suggest.

**Comment by stappersg** [comment]
Meanwhile did #95 get merged.

So this issue should now be retitled to  _what is page is unclear about what Podman does_.

**Comment by wjt** [comment]
Sorry for dropping the ball on this. The extra two sentences here:

> What is Podman? **Podman is a daemonless container engine for developing, managing, and running OCI Containers on your Linux System. Containers can either be run as root or in rootless mode.** Simply put: `alias docker=podman`. More details [here](https://podman.io/whatis.html).

make a *huge* difference, and the linked page clears up more details. Thanks!

**Comment by TomSweeneyRedHat** [comment]
@stappersg yes, #95 was merged.
@wjt thanks for the follow up
