### ISSUE TITLE
podman.io/feed.xml has bad podman.io urls

### ISSUE THREAD

**Issue by mattiasb** [containers/podman.io_old#93]
Hi!

I'm following podman development with my feedreader and the URL's pointing to podman.io look like this most of the time:
```html
<link href="https:/podman.io/feed.xml" rel="self" type="application/atom+xml" />
```
Note the *single* `/` there after `https:`!

This makes the links from my feed reader not working correctly (I end up at `https://podman.io/podman.io/new/2019/04/16/new.html`) 😢

**Comment by TomSweeneyRedHat** [comment]
@mattiasb Thanks for the issue and the PR.  It does look like you've fixed the issue, but will wait for one more LGTM to merge it in.
