### ISSUE TITLE
omg, what is wrong with you

### ISSUE THREAD

**Issue by hook-s3c** [containers/podman.io_old#96]
been on your website - distinct lack of explaining what podman is and what problem it solves

"What is Podman? Simply put: `alias docker=podman`"

my #2 pet peeve after poor setup instructions

thanks!

**Comment by rhatdan** [comment]
@hook-s3c Thanks for your input.  What would you like to see?  PR's to help cleanup and improve documentation are always appreciated.

**Comment by rhatdan** [comment]
How about
`
Podman is a daemonless tool for developing/managing/running OCI Containers on your Linux System.  Containers can either be run as root or in rootless mode.
`
Then link off to a more in depth description?

**Comment by TomSweeneyRedHat** [comment]
#95 is in progress to hopefully help with this.
If you could let me know what issues you're having with the install instructions, I'm happy to try and clear them up.

**Comment by kaceo** [comment]
I only found out about Podman last night from a Youtube clip.  I would like to see a more basic explanation of Podman with less assumption of knowledge of Docker.  Also it would be nice if you spell out whether the current releases of both projects are on feature parity, without having to read through all the blog posts?  I am already deploying Docker (and docker-compose) for the past year and it would be nice to know if switching to Podman is clone-like, say, replacing MySQL with MariaDB or Exim with Postfix, or there are transition details that need to be processed.  I understand docker-compose is not supported, but any documentation on writing the equivalent?

**Comment by TomSweeneyRedHat** [comment]
Fixed with #95.  If you can tell us where the problems with the install instructions are, feel free to reopen this or better yet start a new issue on the Podman Github [issues](https://github.com/containers/libpod/issues).
